name: notes
description: Keep Notes,

publish_to: 'none'

version: 0.0.3+4

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cloud_firestore: ^3.1.0
  encrypt: ^5.0.1
  file_picker: ^4.2.2+1
  firebase_auth: ^3.2.0
  firebase_core: ^1.10.0
  flutter_keyboard_visibility: ^5.1.0
  flutter_secure_storage: ^5.0.0
  flutter_slidable: ^1.0.0
  flutter_spinkit: ^5.1.0
  flutter_svg: ^0.23.0+1
  flutter_tabler_icons: ^1.1.1
  google_sign_in: ^5.2.1
  internet_connection_checker: ^0.0.1+3
  intl: ^0.17.0
  local_auth: ^1.1.8
  logger: ^1.1.0
  permission_handler: ^8.2.6
  provider: ^6.0.1
  sentry_flutter: ^6.1.1
  shared_preferences: ^2.0.8
  sqflite: ^2.0.0+4
  syncfusion_flutter_pdf: ^19.3.53-beta
  url_launcher: ^6.0.12
  uuid: ^3.0.5
  wc_form_validators: ^1.0.0
  keepsettings:
    git:
      url: https://github.com/ProblematicDude/keepsettings.git
dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^1.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/