name: notes
description: Keep Notes,

publish_to: 'none'

version: 0.0.3+4

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #Firebase
  firebase_auth: ^3.3.0
  firebase_core: ^1.10.2
  cloud_firestore: ^3.1.1
  flutter_colorpicker: ^1.0.2
  encrypt: ^5.0.1
  file_picker: ^4.2.7
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.0.0
  flutter_tabler_icons: ^1.1.1
  google_sign_in: ^5.2.1
  intl: ^0.17.0
  local_auth: ^1.1.8
  logger: ^1.1.0
  path: ^1.8.0
  provider: ^6.0.1
  permission_handler: ^8.3.0
  sentry_flutter: ^6.1.2
  shared_preferences: ^2.0.9
  sqflite: ^2.0.1
  url_launcher: ^6.0.17
  uuid: ^3.0.5
  wc_form_validators: ^1.0.0
  pinput: ^1.2.2
  progress_state_button: ^1.0.4
  google_fonts: ^2.1.0


  flutter_slidable:
    git:
      url: https://github.com/nikhilbadyal/flutter_slidable.git
  keepsettings:
    git:
      url: https://github.com/nikhilbadyal/keepsettings.git
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  flutter_native_splash: ^1.3.2
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/