name: notes
description: Keep Notes,

publish_to: 'none'

version: 0.0.3+4

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  file_picker: ^3.0.2+2
  flutter_slidable: ^0.6.0
  flutter_tabler_icons: ^1.1.1
  intl: ^0.17.0
  local_auth: ^1.1.6
  permission_handler: ^8.0.1
  provider: ^5.0.0
  shared_preferences: ^2.0.6
  sqflite: ^2.0.0+3
  url_launcher: ^6.0.6
  encrypt: ^5.0.0
  flutter_secure_storage: ^4.2.0
  syncfusion_flutter_pdf: ^19.1.67-beta
  keepsettings:
    git:
      url: https://github.com/ProblematicDude/keepsettings.git
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/