name: notes
description: Keep Notes,
publish_to: 'none'
version: 0.0.3+4
environment:
  sdk: ">=2.12.0 <3.0.5"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter

  animations: ^2.0.4
  avatar_glow: ^2.0.2
  firebase_auth: ^3.7.0
  firebase_core: ^1.21.1
  cloud_firestore: ^3.4.6
  encrypt: ^5.0.1
  material_design_icons_flutter: ^5.0.6996
  file_picker: ^5.0.1
  eva_icons_flutter: ^3.1.0
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.1.4
  flutter_tabler_icons: ^1.1.1
  google_sign_in: ^5.4.1
  intl: ^0.17.0
  local_auth: ^2.1.2
  logger: ^1.1.0
  path: ^1.8.1
  provider: ^6.0.3
  permission_handler: ^10.0.0
  sentry_flutter: ^6.9.1
  shared_preferences: ^2.0.15
  sqflite: ^2.0.3+1
  url_launcher: ^6.1.5
  uuid: ^3.0.6
  wc_form_validators: ^1.0.0
  pinput: ^2.2.12
  progress_state_button: ^1.0.4
  flutter_slidable: ^2.0.0
  keepsettings:
    git:
      url: https://github.com/nikhilbadyal/keepsettings.git

dev_dependencies:
  test: ^1.21.1
  sqflite_common_ffi: ^2.1.1+1
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.8
  flutter_launcher_icons: ^0.10.0
  flutter_colorpicker: ^1.0.3
  fake_cloud_firestore: ^1.3.1
  firebase_storage_mocks: ^0.5.1
  firebase_auth_mocks: ^0.8.5+1
  google_sign_in_mocks: ^0.2.1
  mockito: ^5.3.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
