name: notes
description: Keep Notes,
publish_to: 'none'
version: 0.0.3+4
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  animations: ^2.0.2
  avatar_glow: ^2.0.2
  firebase_auth: ^3.3.17
  firebase_core: ^1.16.0
  cloud_firestore: ^3.1.14
  encrypt: ^5.0.1
  material_design_icons_flutter: ^5.0.6595
  file_picker: ^4.5.1
  eva_icons_flutter: ^3.1.0
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.0.3
  flutter_tabler_icons: ^1.1.1
  google_sign_in: ^5.3.0
  intl: ^0.17.0
  local_auth: ^2.0.0
  logger: ^1.1.0
  path: ^1.8.0
  provider: ^6.0.2
  permission_handler: ^9.2.0
  sentry_flutter: ^6.5.1
  shared_preferences: ^2.0.13
  sqflite: ^2.0.2+1
  url_launcher: ^6.1.0
  uuid: ^3.0.6
  wc_form_validators: ^1.0.0
  pinput: ^2.2.7
  progress_state_button: ^1.0.4
  google_fonts: ^2.3.2
  flutter_slidable: ^1.2.0
  keepsettings:
    git:
      url: https://github.com/nikhilbadyal/keepsettings.git

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_native_splash: ^2.1.6
  flutter_launcher_icons: ^0.9.2
  flutter_colorpicker: ^1.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
