name: CI

on:
  push:
    paths-ignore:
      - '**/README.md'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: flutter build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          cache-key: flutter
          cache-path: ${{ runner.tool_cache }}/flutter
            # Creating the key.properties file
      - run: |
          echo storePassword=\${{ secrets.STOREPASSWORD }} >> ${{env.PROPERTIES_PATH}}
          echo keyPassword=\${{ secrets.KEYPASSWORD }} > ${{env.PROPERTIES_PATH}}
          echo keyAlias=\${{ secrets.KEYALIAS }} >> ${{env.PROPERTIES_PATH}}
          echo storeFile=\${{ secrets.STOREFILENAME }} >> ${{env.PROPERTIES_PATH}}
      - run: |
          echo "${{ secrets.STOREFILE }}" | base64 --decode > android/app/keepnotes.jks

      - name: Add google json
        run: |
          echo google-services=\${{ secrets.FIREBASE_JSON }} >> ${{env.FIREBASE_PATH}}
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter build apk

env:
  PROPERTIES_PATH: "./android/key.properties"
  FIREBASE_PATH: "./android/app/google-services.json"
