name: CI

on:
  push:
    paths-ignore:
      - '**/README.md'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: flutter build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          cache-key: flutter
          cache-path: ${{ runner.tool_cache }}/flutter
      - name: populate key.properties
        run: |
          echo "${{ secrets.KEY_PROPERTIES_FILE }}" | base64 --decode > ${{env.KEY_PROPERTIES_PATH}}
      - name: populate keystore
        run: |
          echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > ${{env.KEYSTORE_PATH}}
      - name: Populate google-services.json
        run: |
          echo $GOOGLE_SERVICES_JSON_SECRET > ${{env.GOOGLE_SERVICES_JSON_PATH}}
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter build apk

env:
  KEY_PROPERTIES_PATH: "./android/key.properties"
  KEYSTORE_PATH: "./android/app/keepnotes.jks"
  GOOGLE_SERVICES_JSON_PATH: "./android/app/google-services.json"
  GOOGLE_SERVICES_JSON_SECRET: ${{ secrets.GOOGLE_SERVICES_JSON_FILE }}
